SELECT [F_BuildID]
      ,[F_AreaID]
      ,[F_MeterID]
      ,[F_MeterName]
      ,[F_MeterType]
      ,[F_EnergyCode]
      ,[F_TableName]
      ,[F_State]
      ,[F_CreateTime]
      ,[F_CreateUser]
      ,[F_IsHourNeed]
      ,[F_EnergyIndex]
  FROM [EMS_DB].[dbo].[T_ST_MeterInfo]
  WHERE F_EnergyCode = '01E20'
